// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetListenAddress() {
  return window['go']['main']['App']['GetListenAddress']();
}

export function InstallClaudeUserEnv() {
  return window['go']['main']['App']['InstallClaudeUserEnv']();
}

export function LaunchClaudeTerminal(arg1) {
  return window['go']['main']['App']['LaunchClaudeTerminal'](arg1);
}

export function OpenConfigLocation() {
  return window['go']['main']['App']['OpenConfigLocation']();
}

export function SaveProfileConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveProfileConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
