// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetListenAddress():Promise<string>;

export function InstallClaudeUserEnv():Promise<string>;

export function LaunchClaudeTerminal(arg1:string):Promise<string>;

export function OpenConfigLocation():Promise<string>;

export function SaveProfileConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;
